name: Frosti Provision and Deploy 

on: [push]

jobs:
  buildProject:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
            
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build FrostiDemo.csproj --configuration Release --no-restore
      
      - name: Test
        run: dotnet test FrostiDemo.csproj --no-restore --verbosity normal
        
      - name: Publish
        run: dotnet publish FrostiDemo.csproj -c Release --output ./release
        
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: FrostiDe-ppe-eus-WebAppf177785f2
          package: ./release
      
      - name: logout
        run: |
          az logout
